language: csharp

env:
 global:
  - EnableNuGetPackageRestore=true

matrix:
  include:
    - mono: 3.8.0
      env: MONO_V=MONO2
      solution: src/NLog.mono2.sln
    - mono: latest
      env: MONO_V=MONO4
      solution: src/NLog.mono4.sln

  fast_finish: true

before_script: 
- chmod ugo+x build-mono.sh
- chmod ugo+x $TRAVIS_BUILD_DIR/src/.nuget/NuGet.exe

script: ./build-mono.sh

