version: 4.5.0-beta{build}
image: Visual Studio 2017
configuration: Release
clone_folder: c:\projects\nlog
build_script:
- ps: .\build.ps1
test_script:
- ps: .\run-tests.ps1
deploy: off
artifacts:
- path: 'artifacts\*.nupkg'
services:
- mssql2016