version: 4.5.0-{build}
image: Visual Studio 2017
configuration: Release
clone_folder: c:\projects\nlog
environment:
  github_auth_token:
    secure: +vzVo4DsD93fPeSkrIL12KQsq2VJrge4ZSt3KanSxtnifHsBXYmGko4Ck00sVOqD
  sonar_token:
    secure: GBaeujJgXPbcDto3kyJXpwrTJdPNKNOjwzyzAGNvvKYg+X/S3anpG+8qKMBjjGFI

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'

build_script:
  - ps: .\build.ps1
  - ps: .\run-sonar.ps1

test_script:
  - ps: $runTests = $true;
  - ps: $last = git log -1 --pretty=%B;if ($last -match 'skip tests') {Write-output "skipping tests";$runTests = $false}
  - ps: if($runTests) { .\check-file-headers.ps1}
  - ps: if($runTests) { .\run-tests.ps1}
  - ps: if($runTests) { .\run-opencover.ps1}

cache:
  - src\packages -> **\packages.config
  - c:\projects\nlog\appveyor.sonar\cache

services:
  - mssql2016

artifacts:
  - path: 'artifacts\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: DtVDH1ZfIR8E2oDLeSPxfn0WFXw3MCv4WhLkkQQl9LfEHswb5sdxdCYodNKhrKik
  artifact: /.*\.nupkg/
  on:
    branch: master